apiVersion: v1
kind: Service
metadata:
  name: view-svc
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 80
      nodePort: 30005
  selector:
    app: view-api
  clusterIP: 10.107.154.35
  type: NodePort
