apiVersion: apps/v1
kind: Deployment
metadata:
  name: view-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: view-api
  template:
    metadata:
      labels:
        app: view-api
    spec:
      containers:
        - name: view-api
          image: sktellecom/ms-test:view-api
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /readiness
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: DATE
              value: 'DATE_STRING'
      imagePullSecrets:
        - name: ms-secret
